rain <- rainbow(2)
r <- function (i) rain[i]
pdf("test.pdf")
range <- seq(0,20,length.out=1000)
f <- function(lambda) dpois(range,lambda=lambda)
f <- function(lambda) dexp(range,rate=lambda)
data <- f(0.45)
# data <- rbind(data,f(0.75))
# data <- rbind(data,f(1.0))
# data <- rbind(data,f(2.0))
# barplot(data,beside=T,col=rainbow(nrow(data)))
curve(0.65*exp(-0.65*x),from=0,to=10,col=r(1))
curve(1.65*exp(-1.65*x),from=0,to=10,col=r(2),add=T)
dev.off()
system("xdg-open test.pdf")
