library(lattice,lib.loc='.')
# ?wireframe
# rangex <- seq(-1,1,,500)
# rangey <- seq(-1,1,,500)
# f <- function (x,y) sqrt(1-x^2-y^2)
# g <- expand.grid(x=rangex,y=rangey)
# g$z <- f(g$x,g$y)
# g$z2 <- -g$z
t <- seq(0,2*pi,,115)
p <- seq(0,2*pi,,75)
x <- outer(t,p,function (u,v) (3+cos(v))*cos(u))
y <- outer(t,p,function (u,v) (3+cos(v))*sin(u))
z <- outer(t,p,function (u,v) sin(v))
rng <- function (xs) sum(abs(range(xs)))
aspct <- c(rng(y)/rng(x),rng(z)/rng(x))
png("test.png",w=1380,h=1380)
wireframe(z ~ x+y, drape=T, aspect=aspct, col.regions=rainbow(100),xlab='x',ylab='y',zlab='z',scales=list(draw=F), screen = list(z = -20, x=-70))
dev.off()
system("xdg-open test.png")
